[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish -c Release -o ./publish"]

[start]
cmd = "cd ./publish && dotnet Control-de-Parqueo.dll"

